// Paste your Firebase web app config here as `window.firebaseConfig`.
// To obtain: Firebase Console -> Project Settings -> SDK setup and configuration -> Config
// Example (replace the REPLACE_* values with your project's values):
window.firebaseConfig = window.firebaseConfig || {
	apiKey: "AIzaSyDh0ho6jDmThHMDvCVNL7z4EJHqXJ2B-bw",
	authDomain: "khtn9-2a54e.firebaseapp.com",
	projectId: "khtn9-2a54e",
	storageBucket: "khtn9-2a54e.firebasestorage.app",
	messagingSenderId: "653034367978",
	appId: "1:653034367978:web:0853d82dd621bcc12e2093",
	measurementId: "G-LYQ8V7E408"
};

// Quick validator: if placeholders remain, Firebase init will be skipped and a console hint shown.
// Quick validator: if placeholders remain, Firebase init will be skipped and a console hint shown.
if (window.firebaseConfig && window.firebaseConfig.apiKey && window.firebaseConfig.apiKey.startsWith('REPLACE')) {
	console.warn('firebase-config: placeholder values detected — paste your Firebase web app config into js/firebase-config.js');
}

// Note: project uses the compat SDK (firebase-app-compat.js). The object above
// is the standard web config generated by Firebase Console and is ready to use.
